# Generated by Django 3.1.2 on 2020-10-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
