# Generated by Django 3.1.2 on 2020-10-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_blogs_clients_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='author',
            new_name='bauthor',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='date',
            new_name='bdate',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='description',
            new_name='bdescription',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='images',
            new_name='bimages',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='title',
            new_name='btitle',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='description',
            new_name='cdescription',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='designation',
            new_name='cdesignation',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='images',
            new_name='cimages',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='date',
            new_name='gdate',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='description',
            new_name='gdescription',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='images',
            new_name='gimages',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='sdescription',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='images',
            new_name='simages',
        ),
    ]
