# Generated by Django 3.1.2 on 2020-10-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20201018_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='bauthor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='bdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='bdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='bimages',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='btitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='cdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='cdesignation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='cimages',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='cname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='gdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='gdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='gimages',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='sdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='simages',
            new_name='images',
        ),
    ]
