# Generated by Django 3.1.2 on 2020-10-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20201018_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
