# Generated by Django 3.1.2 on 2020-10-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_delete_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('shortlist', models.BooleanField(default=False)),
            ],
        ),
    ]
