# Generated by Django 3.1.2 on 2020-10-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20201018_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='shortlist',
            field=models.BooleanField(default=False),
        ),
    ]
