# Generated by Django 3.1.2 on 2020-10-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_blog_shortlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='shortlist',
        ),
    ]
