# Generated by Django 3.1.2 on 2020-11-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='servicename',
            field=models.CharField(max_length=30),
        ),
    ]
