# Generated by Django 3.1.2 on 2020-11-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20201111_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='images',
        ),
    ]
