# Generated by Django 3.1.2 on 2020-11-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20201111_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='servicename',
            new_name='title',
        ),
    ]
