# Generated by Django 3.1.2 on 2020-11-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20201111_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
