# Generated by Django 3.1.2 on 2020-11-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_auto_20201125_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
